/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *idrechercher_entry1;
  GtkWidget *label6;
  GtkWidget *modifier_button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *supprimer_button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *affecterservicebutton2;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label64;
  GtkWidget *actualiser_button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *rechercher_button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *ajouter_button1_;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *label1;
  GtkWidget *fixed2;
  GtkWidget *idservices_entry2;
  GtkObject *prix_spinbutton1_adj;
  GtkWidget *prix_spinbutton1;
  GtkObject *jj_spinbutton2_adj;
  GtkWidget *jj_spinbutton2;
  GtkObject *mm_spinbutton3_adj;
  GtkWidget *mm_spinbutton3;
  GtkObject *aa_spinbutton4_adj;
  GtkWidget *aa_spinbutton4;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label12;
  GtkWidget *checkbutton1;
  GtkWidget *ajouter_button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label20;
  GtkWidget *carte_radiobutton1;
  GSList *carte_radiobutton1_group = NULL;
  GtkWidget *carte_radiobutton2;
  GtkWidget *apresmidi_radiobutton4;
  GSList *apresmidi_radiobutton4_group = NULL;
  GtkWidget *matin_radiobutton3;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *typesajou_comboboxentry1;
  GtkWidget *annuler_button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label21;
  GtkWidget *acceuiservicebutton2;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image24;
  GtkWidget *label65;
  GtkWidget *fixed6;
  GtkWidget *image28;
  GtkWidget *label2;
  GtkWidget *fixed3;
  GtkWidget *idmod_entry3;
  GtkObject *prixmod_spinbutton5_adj;
  GtkWidget *prixmod_spinbutton5;
  GtkObject *jj_spinbutton6_adj;
  GtkWidget *jj_spinbutton6;
  GtkObject *mm_spinbutton7_adj;
  GtkWidget *mm_spinbutton7;
  GtkObject *aa_spinbutton8_adj;
  GtkWidget *aa_spinbutton8;
  GtkWidget *label22;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *checkbutton2;
  GtkWidget *anuller_button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label31;
  GtkWidget *modifier_button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label30;
  GtkWidget *label28;
  GtkWidget *cartemod_radiobutton5;
  GSList *cartemod_radiobutton5_group = NULL;
  GtkWidget *especesmod_radiobutton6;
  GtkWidget *matinmod_radiobutton7;
  GtkWidget *apresmidi_radiobutton8;
  GtkWidget *typemod_comboboxentry2;
  GtkWidget *verifier;
  GtkWidget *modfierservicebutton3;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image25;
  GtkWidget *label66;
  GtkWidget *label3;
  GtkWidget *fixed4;
  GtkWidget *idservicessup_entry4;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *supprimer_button10;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label35;
  GtkWidget *anuller_button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label36;
  GtkWidget *button4;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image26;
  GtkWidget *label67;
  GtkWidget *label4;
  GtkWidget *fixed5;
  GtkWidget *idaffecter_entry5;
  GtkWidget *idparking_entry6;
  GtkWidget *label38;
  GtkWidget *treeviewaffecter;
  GtkWidget *annuleraff_button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label41;
  GtkWidget *button1;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label42;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *affecter_button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label40;
  GtkWidget *affservicebutton5;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image27;
  GtkWidget *label68;
  GtkWidget *label5;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_LEFT);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 24, 184);
  gtk_widget_set_size_request (treeview1, 1152, 280);

  idrechercher_entry1 = gtk_entry_new ();
  gtk_widget_show (idrechercher_entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), idrechercher_entry1, 240, 504);
  gtk_widget_set_size_request (idrechercher_entry1, 272, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (idrechercher_entry1), 8226);

  label6 = gtk_label_new_with_mnemonic (_("<span  color='red'> Bienvenu aux services compl\303\251mentaires </span>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 104, 32);
  gtk_widget_set_size_request (label6, 432, 97);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  modifier_button2 = gtk_button_new ();
  gtk_widget_show (modifier_button2);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_button2, 152, 112);
  gtk_widget_set_size_request (modifier_button2, 136, 61);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier_button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  supprimer_button3 = gtk_button_new ();
  gtk_widget_show (supprimer_button3);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer_button3, 296, 112);
  gtk_widget_set_size_request (supprimer_button3, 192, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer_button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  affecterservicebutton2 = gtk_button_new ();
  gtk_widget_show (affecterservicebutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), affecterservicebutton2, 504, 104);
  gtk_widget_set_size_request (affecterservicebutton2, 192, 69);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (affecterservicebutton2), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("affecter"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox22), label64, FALSE, FALSE, 0);

  actualiser_button4 = gtk_button_new ();
  gtk_widget_show (actualiser_button4);
  gtk_fixed_put (GTK_FIXED (fixed1), actualiser_button4, 704, 104);
  gtk_widget_set_size_request (actualiser_button4, 232, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (actualiser_button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("actualiser "));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  rechercher_button5 = gtk_button_new ();
  gtk_widget_show (rechercher_button5);
  gtk_fixed_put (GTK_FIXED (fixed1), rechercher_button5, 16, 504);
  gtk_widget_set_size_request (rechercher_button5, 200, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (rechercher_button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  ajouter_button1_ = gtk_button_new ();
  gtk_widget_show (ajouter_button1_);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_button1_, 16, 112);
  gtk_widget_set_size_request (ajouter_button1_, 128, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_button1_), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("ajouter "));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("afficher "));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  idservices_entry2 = gtk_entry_new ();
  gtk_widget_show (idservices_entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), idservices_entry2, 168, 144);
  gtk_widget_set_size_request (idservices_entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idservices_entry2), 8226);

  prix_spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  prix_spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (prix_spinbutton1_adj), 1, 0);
  gtk_widget_show (prix_spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), prix_spinbutton1, 112, 280);
  gtk_widget_set_size_request (prix_spinbutton1, 60, 27);

  jj_spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jj_spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (jj_spinbutton2_adj), 1, 0);
  gtk_widget_show (jj_spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), jj_spinbutton2, 96, 448);
  gtk_widget_set_size_request (jj_spinbutton2, 60, 27);

  mm_spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mm_spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (mm_spinbutton3_adj), 1, 0);
  gtk_widget_show (mm_spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), mm_spinbutton3, 96, 488);
  gtk_widget_set_size_request (mm_spinbutton3, 60, 27);

  aa_spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  aa_spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (aa_spinbutton4_adj), 1, 0);
  gtk_widget_show (aa_spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), aa_spinbutton4, 96, 544);
  gtk_widget_set_size_request (aa_spinbutton4, 60, 27);

  label15 = gtk_label_new (_("Prix"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 104, 248);
  gtk_widget_set_size_request (label15, 49, 17);

  label16 = gtk_label_new (_("methode de payment "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 80, 328);
  gtk_widget_set_size_request (label16, 160, 16);

  label17 = gtk_label_new (_("Duree estimee"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 72, 416);
  gtk_widget_set_size_request (label17, 129, 17);

  label18 = gtk_label_new (_("heure"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 272, 416);
  gtk_widget_set_size_request (label18, 49, 17);

  label19 = gtk_label_new (_("confrimer "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 32, 608);
  gtk_widget_set_size_request (label19, 121, 25);

  label12 = gtk_label_new_with_mnemonic (_("<span  color='red'> ajouter services </span>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 96, 48);
  gtk_widget_set_size_request (label12, 224, 57);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("acees"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 152, 608);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  ajouter_button6 = gtk_button_new ();
  gtk_widget_show (ajouter_button6);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter_button6, 72, 656);
  gtk_widget_set_size_request (ajouter_button6, 104, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ajouter_button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("ajouter "));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox6), label20, FALSE, FALSE, 0);

  carte_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("carte"));
  gtk_widget_show (carte_radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), carte_radiobutton1, 96, 368);
  gtk_widget_set_size_request (carte_radiobutton1, 116, 24);
  gtk_button_set_focus_on_click (GTK_BUTTON (carte_radiobutton1), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (carte_radiobutton1), carte_radiobutton1_group);
  carte_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (carte_radiobutton1));

  carte_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("especes "));
  gtk_widget_show (carte_radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), carte_radiobutton2, 240, 368);
  gtk_widget_set_size_request (carte_radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (carte_radiobutton2), carte_radiobutton1_group);
  carte_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (carte_radiobutton2));

  apresmidi_radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("apresmidi"));
  gtk_widget_show (apresmidi_radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), apresmidi_radiobutton4, 272, 488);
  gtk_widget_set_size_request (apresmidi_radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (apresmidi_radiobutton4), apresmidi_radiobutton4_group);
  apresmidi_radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (apresmidi_radiobutton4));

  matin_radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("matin "));
  gtk_widget_show (matin_radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), matin_radiobutton3, 272, 448);
  gtk_widget_set_size_request (matin_radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (matin_radiobutton3), apresmidi_radiobutton4_group);
  apresmidi_radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (matin_radiobutton3));

  label14 = gtk_label_new (_("types services"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 40, 200);
  gtk_widget_set_size_request (label14, 128, 25);

  label13 = gtk_label_new (_("Id services "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 48, 144);
  gtk_widget_set_size_request (label13, 128, 33);

  typesajou_comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (typesajou_comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), typesajou_comboboxentry1, 168, 200);
  gtk_widget_set_size_request (typesajou_comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (typesajou_comboboxentry1), _("Lavage_de_voiture "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (typesajou_comboboxentry1), _("Paiement_simplifi\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (typesajou_comboboxentry1), _("R\303\251servation_en_ligne "));

  annuler_button7 = gtk_button_new ();
  gtk_widget_show (annuler_button7);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler_button7, 224, 656);
  gtk_widget_set_size_request (annuler_button7, 98, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (annuler_button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox7), label21, FALSE, FALSE, 0);

  acceuiservicebutton2 = gtk_button_new ();
  gtk_widget_show (acceuiservicebutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), acceuiservicebutton2, 376, 656);
  gtk_widget_set_size_request (acceuiservicebutton2, 168, 37);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (acceuiservicebutton2), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image24 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox23), image24, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("acceuil "));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox23), label65, FALSE, FALSE, 0);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed6, 600, 128);
  gtk_widget_set_size_request (fixed6, 400, 400);

  image28 = create_pixmap (window1, "/home/wassim/p.jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed6), image28, 0, 0);
  gtk_widget_set_size_request (image28, 400, 400);

  label2 = gtk_label_new (_("ajouter "));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  idmod_entry3 = gtk_entry_new ();
  gtk_widget_show (idmod_entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), idmod_entry3, 144, 128);
  gtk_widget_set_size_request (idmod_entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idmod_entry3), 8226);

  prixmod_spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  prixmod_spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (prixmod_spinbutton5_adj), 1, 0);
  gtk_widget_show (prixmod_spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), prixmod_spinbutton5, 80, 288);
  gtk_widget_set_size_request (prixmod_spinbutton5, 60, 27);

  jj_spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jj_spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (jj_spinbutton6_adj), 1, 0);
  gtk_widget_show (jj_spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), jj_spinbutton6, 64, 464);
  gtk_widget_set_size_request (jj_spinbutton6, 60, 27);

  mm_spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mm_spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (mm_spinbutton7_adj), 1, 0);
  gtk_widget_show (mm_spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), mm_spinbutton7, 64, 496);
  gtk_widget_set_size_request (mm_spinbutton7, 60, 27);

  aa_spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  aa_spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (aa_spinbutton8_adj), 1, 0);
  gtk_widget_show (aa_spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), aa_spinbutton8, 64, 528);
  gtk_widget_set_size_request (aa_spinbutton8, 60, 27);

  label22 = gtk_label_new_with_mnemonic (_("<span  color='red'> modifier services  </span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 144, 40);
  gtk_widget_set_size_request (label22, 224, 57);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label25 = gtk_label_new (_("Prix"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 80, 256);
  gtk_widget_set_size_request (label25, 49, 17);

  label26 = gtk_label_new (_("methode de payment "));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 64, 320);
  gtk_widget_set_size_request (label26, 144, 49);

  label27 = gtk_label_new (_("duree estimee"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 72, 432);
  gtk_widget_set_size_request (label27, 120, 17);

  label29 = gtk_label_new (_("confrimer "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 64, 592);
  gtk_widget_set_size_request (label29, 89, 17);

  label23 = gtk_label_new (_("ID services "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 40, 129);
  gtk_widget_set_size_request (label23, 88, 16);

  label24 = gtk_label_new (_("types services "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 32, 200);
  gtk_widget_set_size_request (label24, 104, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("acees "));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 176, 592);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  anuller_button9 = gtk_button_new ();
  gtk_widget_show (anuller_button9);
  gtk_fixed_put (GTK_FIXED (fixed3), anuller_button9, 208, 648);
  gtk_widget_set_size_request (anuller_button9, 120, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (anuller_button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox9), label31, FALSE, FALSE, 0);

  modifier_button8 = gtk_button_new ();
  gtk_widget_show (modifier_button8);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier_button8, 72, 656);
  gtk_widget_set_size_request (modifier_button8, 96, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (modifier_button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox8), label30, FALSE, FALSE, 0);

  label28 = gtk_label_new (_("heure "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 208, 456);
  gtk_widget_set_size_request (label28, 49, 17);

  cartemod_radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("carte"));
  gtk_widget_show (cartemod_radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), cartemod_radiobutton5, 64, 376);
  gtk_widget_set_size_request (cartemod_radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cartemod_radiobutton5), cartemod_radiobutton5_group);
  cartemod_radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cartemod_radiobutton5));

  especesmod_radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("especes "));
  gtk_widget_show (especesmod_radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), especesmod_radiobutton6, 224, 376);
  gtk_widget_set_size_request (especesmod_radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (especesmod_radiobutton6), cartemod_radiobutton5_group);
  cartemod_radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (especesmod_radiobutton6));

  matinmod_radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("matin "));
  gtk_widget_show (matinmod_radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), matinmod_radiobutton7, 208, 480);
  gtk_widget_set_size_request (matinmod_radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (matinmod_radiobutton7), apresmidi_radiobutton4_group);
  apresmidi_radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (matinmod_radiobutton7));

  apresmidi_radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("apresmidi"));
  gtk_widget_show (apresmidi_radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), apresmidi_radiobutton8, 208, 528);
  gtk_widget_set_size_request (apresmidi_radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (apresmidi_radiobutton8), apresmidi_radiobutton4_group);
  apresmidi_radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (apresmidi_radiobutton8));

  typemod_comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (typemod_comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed3), typemod_comboboxentry2, 144, 192);
  gtk_widget_set_size_request (typemod_comboboxentry2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (typemod_comboboxentry2), _("Lavage_de_voiture "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (typemod_comboboxentry2), _("Paiement_simplifi\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (typemod_comboboxentry2), _("R\303\251servation_en_ligne "));

  verifier = gtk_button_new_with_mnemonic (_("verifier"));
  gtk_widget_show (verifier);
  gtk_fixed_put (GTK_FIXED (fixed3), verifier, 328, 120);
  gtk_widget_set_size_request (verifier, 112, 37);

  modfierservicebutton3 = gtk_button_new ();
  gtk_widget_show (modfierservicebutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), modfierservicebutton3, 344, 648);
  gtk_widget_set_size_request (modfierservicebutton3, 120, 37);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (modfierservicebutton3), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image25 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox24), image25, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("acceuil "));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox24), label66, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("modifier "));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  idservicessup_entry4 = gtk_entry_new ();
  gtk_widget_show (idservicessup_entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), idservicessup_entry4, 152, 128);
  gtk_widget_set_size_request (idservicessup_entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idservicessup_entry4), 8226);

  label32 = gtk_label_new (_("<span font_desc=\"20\" color='navy'>supprimer services</span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 128, 32);
  gtk_widget_set_size_request (label32, 280, 57);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label33 = gtk_label_new (_("ID services "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 32, 120);
  gtk_widget_set_size_request (label33, 104, 41);

  label34 = gtk_label_new (_("vouler-vous supprimer ce donneurs "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 0, 168);
  gtk_widget_set_size_request (label34, 344, 56);

  supprimer_button10 = gtk_button_new ();
  gtk_widget_show (supprimer_button10);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_button10, 48, 240);
  gtk_widget_set_size_request (supprimer_button10, 96, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (supprimer_button10), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  anuller_button11 = gtk_button_new ();
  gtk_widget_show (anuller_button11);
  gtk_fixed_put (GTK_FIXED (fixed4), anuller_button11, 216, 224);
  gtk_widget_set_size_request (anuller_button11, 136, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (anuller_button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 424, 216);
  gtk_widget_set_size_request (button4, 176, 61);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button4), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image26 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox25), image26, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("acceuil"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox25), label67, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("supprimer "));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  idaffecter_entry5 = gtk_entry_new ();
  gtk_widget_show (idaffecter_entry5);
  gtk_fixed_put (GTK_FIXED (fixed5), idaffecter_entry5, 192, 144);
  gtk_widget_set_size_request (idaffecter_entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idaffecter_entry5), 8226);

  idparking_entry6 = gtk_entry_new ();
  gtk_widget_show (idparking_entry6);
  gtk_fixed_put (GTK_FIXED (fixed5), idparking_entry6, 192, 208);
  gtk_widget_set_size_request (idparking_entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idparking_entry6), 8226);

  label38 = gtk_label_new (_("ID services "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 96, 144);
  gtk_widget_set_size_request (label38, 88, 25);

  treeviewaffecter = gtk_tree_view_new ();
  gtk_widget_show (treeviewaffecter);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewaffecter, 432, 120);
  gtk_widget_set_size_request (treeviewaffecter, 440, 320);

  annuleraff_button13 = gtk_button_new ();
  gtk_widget_show (annuleraff_button13);
  gtk_fixed_put (GTK_FIXED (fixed5), annuleraff_button13, 208, 272);
  gtk_widget_set_size_request (annuleraff_button13, 96, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (annuleraff_button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed5), button1, 792, 72);
  gtk_widget_set_size_request (button1, 152, 45);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button1), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("actualiser affecter "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox14), label42, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("l<span font_desc=\"20\" color='navy'>Affecter service pour une reservation</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 96, 32);
  gtk_widget_set_size_request (label37, 496, 41);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label39 = gtk_label_new (_("iD reservation  "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 88, 224);
  gtk_widget_set_size_request (label39, 80, 16);

  affecter_button12 = gtk_button_new ();
  gtk_widget_show (affecter_button12);
  gtk_fixed_put (GTK_FIXED (fixed5), affecter_button12, 88, 272);
  gtk_widget_set_size_request (affecter_button12, 96, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (affecter_button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("affecter "));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox12), label40, FALSE, FALSE, 0);

  affservicebutton5 = gtk_button_new ();
  gtk_widget_show (affservicebutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), affservicebutton5, 336, 264);
  gtk_widget_set_size_request (affservicebutton5, 80, 53);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (affservicebutton5), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image27 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox26), image27, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("acceuil "));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox26), label68, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("taches supplemaintres "));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier_button2, "clicked",
                    G_CALLBACK (on_modifier_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_button3, "clicked",
                    G_CALLBACK (on_supprimer_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) affecterservicebutton2, "clicked",
                    G_CALLBACK (on_affecterservicebutton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser_button4, "clicked",
                    G_CALLBACK (on_actualiser_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher_button5, "clicked",
                    G_CALLBACK (on_rechercher_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_button1_, "clicked",
                    G_CALLBACK (on_ajouter_button1__clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajouter_button6, "clicked",
                    G_CALLBACK (on_ajouter_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) carte_radiobutton1, "toggled",
                    G_CALLBACK (on_carte_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) carte_radiobutton2, "toggled",
                    G_CALLBACK (on_carte_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) annuler_button7, "clicked",
                    G_CALLBACK (on_annuler_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) acceuiservicebutton2, "clicked",
                    G_CALLBACK (on_acceuiservicebutton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) anuller_button9, "clicked",
                    G_CALLBACK (on_anuller_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_button8, "clicked",
                    G_CALLBACK (on_modifier_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) cartemod_radiobutton5, "toggled",
                    G_CALLBACK (on_cartemod_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) especesmod_radiobutton6, "toggled",
                    G_CALLBACK (on_especesmod_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) matinmod_radiobutton7, "toggled",
                    G_CALLBACK (on_matinmod_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) apresmidi_radiobutton8, "toggled",
                    G_CALLBACK (on_apresmidi_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) verifier, "clicked",
                    G_CALLBACK (on_verifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) modfierservicebutton3, "clicked",
                    G_CALLBACK (on_modfierservicebutton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_button10, "clicked",
                    G_CALLBACK (on_supprimer_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewaffecter, "row_activated",
                    G_CALLBACK (on_treeviewaffecter_row_activated),
                    NULL);
  g_signal_connect ((gpointer) annuleraff_button13, "clicked",
                    G_CALLBACK (on_annuleraff_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) affecter_button12, "clicked",
                    G_CALLBACK (on_affecter_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) affservicebutton5, "clicked",
                    G_CALLBACK (on_affservicebutton5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, idrechercher_entry1, "idrechercher_entry1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, modifier_button2, "modifier_button2");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, supprimer_button3, "supprimer_button3");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, affecterservicebutton2, "affecterservicebutton2");
  GLADE_HOOKUP_OBJECT (window1, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window1, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, actualiser_button4, "actualiser_button4");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, rechercher_button5, "rechercher_button5");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, ajouter_button1_, "ajouter_button1_");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, idservices_entry2, "idservices_entry2");
  GLADE_HOOKUP_OBJECT (window1, prix_spinbutton1, "prix_spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, jj_spinbutton2, "jj_spinbutton2");
  GLADE_HOOKUP_OBJECT (window1, mm_spinbutton3, "mm_spinbutton3");
  GLADE_HOOKUP_OBJECT (window1, aa_spinbutton4, "aa_spinbutton4");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, ajouter_button6, "ajouter_button6");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, carte_radiobutton1, "carte_radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, carte_radiobutton2, "carte_radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, apresmidi_radiobutton4, "apresmidi_radiobutton4");
  GLADE_HOOKUP_OBJECT (window1, matin_radiobutton3, "matin_radiobutton3");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, typesajou_comboboxentry1, "typesajou_comboboxentry1");
  GLADE_HOOKUP_OBJECT (window1, annuler_button7, "annuler_button7");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, acceuiservicebutton2, "acceuiservicebutton2");
  GLADE_HOOKUP_OBJECT (window1, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window1, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, idmod_entry3, "idmod_entry3");
  GLADE_HOOKUP_OBJECT (window1, prixmod_spinbutton5, "prixmod_spinbutton5");
  GLADE_HOOKUP_OBJECT (window1, jj_spinbutton6, "jj_spinbutton6");
  GLADE_HOOKUP_OBJECT (window1, mm_spinbutton7, "mm_spinbutton7");
  GLADE_HOOKUP_OBJECT (window1, aa_spinbutton8, "aa_spinbutton8");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window1, anuller_button9, "anuller_button9");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, modifier_button8, "modifier_button8");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, cartemod_radiobutton5, "cartemod_radiobutton5");
  GLADE_HOOKUP_OBJECT (window1, especesmod_radiobutton6, "especesmod_radiobutton6");
  GLADE_HOOKUP_OBJECT (window1, matinmod_radiobutton7, "matinmod_radiobutton7");
  GLADE_HOOKUP_OBJECT (window1, apresmidi_radiobutton8, "apresmidi_radiobutton8");
  GLADE_HOOKUP_OBJECT (window1, typemod_comboboxentry2, "typemod_comboboxentry2");
  GLADE_HOOKUP_OBJECT (window1, verifier, "verifier");
  GLADE_HOOKUP_OBJECT (window1, modfierservicebutton3, "modfierservicebutton3");
  GLADE_HOOKUP_OBJECT (window1, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window1, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label66, "label66");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, idservicessup_entry4, "idservicessup_entry4");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, supprimer_button10, "supprimer_button10");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, anuller_button11, "anuller_button11");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, idaffecter_entry5, "idaffecter_entry5");
  GLADE_HOOKUP_OBJECT (window1, idparking_entry6, "idparking_entry6");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, treeviewaffecter, "treeviewaffecter");
  GLADE_HOOKUP_OBJECT (window1, annuleraff_button13, "annuleraff_button13");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, affecter_button12, "affecter_button12");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, affservicebutton5, "affservicebutton5");
  GLADE_HOOKUP_OBJECT (window1, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window1, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window1, image27, "image27");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");

  return window1;
}

